name: Run ESLint on Pull Requests

on:
    - pull_request

jobs:
    build:
        name: Run ESLint
        runs-on: ubuntu-latest
        steps:
            # Check out the repository
            - uses: actions/checkout@v1

            # Install Node.js
            - uses: actions/setup-node@v1
              with:
                  node-version: 12

            # Install your dependencies
            - run: yarn lint

            # Run ESLint using latest action
            - uses: eslint/github-action@draft
              env:
                  ESLINT_DRAFT: 1
