name: ESLint

on:
    - pull_request

jobs:
    build:
        name: ESLint
        runs-on: ubuntu-latest
        steps:
            # Check out the repository
            - uses: actions/checkout@v1
            # Install Node.js
            - uses: actions/setup-node@v1
              with:
                  node-version: 16
            # Install your dependencies
            - name: Get UNAME
            - run: uname
            - name: Install Packages
              run: yarn add eslint@^7.31.0 eslint-plugin-react@^7.24.0
            # Lint
            - run: yarn lint
